<a href="https://colab.research.google.com/github/Android998/TensorFlow2.3/blob/master/BasesTensorFlow2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np


In [ ]:
tf.__version__

'2.3.0'

## **Constantes**

### Definir una constante

In [ ]:
#Definir una constante en Tensorflow 2.3
tensor_2 = tf.constant([[23, 4], [3,5]])

In [ ]:
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [ 3,  5]], dtype=int32)>

In [ ]:
tensor_2.shape

TensorShape([2, 2])

### Consultar los valores de una constante

In [ ]:
tensor_2.numpy()

array([[23,  4],
       [ 3,  5]], dtype=int32)

In [ ]:
numpy_tensor = np.array([[23, 4],[3, 5]])

In [ ]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [ ]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [ 3,  5]])>

## **Variable**

#### **Definir una variable**

In [ ]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

## **Consultar valores de una variable**

In [ ]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

## **Cambiar un valor especifico de una variable**

In [ ]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

## **Operaciones con tensores**

In [ ]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### **Sumar un escalar a un tensor**

In [ ]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### **Múltiplicar un escalar a un tensor**

In [ ]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### **Utilizar funciones de Numpy sobre tensores de TensorFlow**

In [ ]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### **Producto escalar entre dos tensores**

In [ ]:
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [ 3,  5]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
#Producto entre matrices 
np.dot(tensor, tensor_2)

array([[29, 14],
       [81, 32]], dtype=int32)

## **Strings en TensorFlow 2.3**

In [ ]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### **Operaciones simples con strings**

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### **Almacenaje arrays de strings**

In [ ]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
